### Get all users

GET http://localhost:3001/api/users

### Authentication Success
POST http://localhost:3001/api/token-auth
Content-Type: application/json

{
    "username": "michaelmyers123",
    "password": "halloween"
}

### Authentication Failure (Wrong credentials)
POST http://localhost:3001/api/token-auth
Content-Type: application/json

{
    "username": "michaelmyers123",
    "password": "asdf"
}

### Authentication Failure (Not enough information)
POST http://localhost:3001/api/token-auth
Content-Type: application/json

{
    "username": "michaelmyers123"
}
