@startuml Bank Class Diagram

title "Bank Models"

class Bank {
    This represents the bank's database.
    ---
    + ""partner-code"": ""String""
    + ""users"": ""Array<User>""
    + ""loyaltyProgramMemberships"": ""Array<LoyaltyProgramMembership>""
    + ""loyaltyPrograms"": ""Array<LoyaltyProgram>""
    + ""transfers"": ""Array<Transfer>""
}

class User {
    This represents a user of the bank.
    ---
    + ""userId"": ""String""
    + ""username"": ""String""
    + ""firstName"": ""String""
    + ""lastName"": ""String""
    + {field} ""password"": ""String"" (hashed)
    + ""points"": ""Number""
    + {field} ""loyaltyProgramMembershipIds"": ""Array<Number>"" \nIDs of memberships registered to this user
    + {field} ""transferIds"": ""Array<Number>"" \nIDs of transfers made by this user
}

class LoyaltyProgram {
    This represents a single loyalty program.
    ---
    + ""loyaltyProgramId"": ""String""
    + {field} ""exchange-rate"": ""Number"" (ratio TC points/Program points)
}

class LoyaltyProgramMembership {
    This represents a membership registered under\n a specific Bank User for a specific Loyalty Program.
    ---
    + ""userId"": ""String""\nID of Bank User this membership is registered to.
    + ""loyaltyProgramMemberId"": ""String""\nID of loyalty program membership.
    + ""loyaltyProgramId"": ""String""\nID of loyalty program.
}

class Transfer {
    This represents a single accrual transfer made by a specific bank user\nunder a specific program membership.
    ---
    + ""transferId"": ""String""
    + ""loyaltyProgramMemberId"": ""String""
    + ""status"": ""String""
}

Bank "1" *-- "0..*" User : ""users"" contains >
Bank "1" *---- "0..*" LoyaltyProgramMembership : ""loyaltyProgramMemberships"" contains >
Bank "1" *-- "0..*" Transfer : ""transfers"" contains >
Bank "1" *-- "0..*" LoyaltyProgram : ""loyaltyPrograms"" contains >

User "1"*---"0..*" LoyaltyProgramMembership : ""loyaltyProgramMembershipIds"" contains\n""loyaltyProgramMembershipId"" of... \n >
User "1"*---"0..*" Transfer : ""transferIds"" contains ""transferId"" of...\n >

LoyaltyProgram --- LoyaltyProgramMembership : has ""loyaltyProgramId"" <

@enduml