@startuml
class TC {
    - Array<String> pointsIDValidationFormat
    - Array<String> loyaltyPrograms    
    + getTransferByRef(String referenceNumber, String partnerCode)
    + createTransfer(Document transfer)
    + getLoyaltyByProgramId(String programID)
    + getLPIDValidation(String pointsID, String ProgramID)
    + sendDailyTransfers(CSV transfers)
    + updateDailyTransfers(URL webhook, JSON transferData)
}

class Transfer {
    - String _id
    - String memberId
    - String memberFirstName
    - String MemberLastName
    - String transferDate
    - String amount
    - String referenceNumber
    - String partnerCode
    - String loyaltyProgram
    - String status
    - String outcomeDetails
    - String sentToSFTP
}

class Loyalty_Program {
    - String _id
    - String programId
    - String programName
    - String currencyName
    - String processingTime
    - String description
    - String enrollmentLink
    - String tncLink
    - String imgSrc
}
class Bank_Partner {
    - String _id
    - String bankId
    - String bankName
    - String bankCredentials
}

TC "0..1" --- "0..*" Transfer
TC "0..1" --- "0..*" Loyalty_Program
TC "0..1" --- "0..*" Bank_Partner
@enduml