### Authentication Success
POST http://localhost:3002/api/bank/send-transfer
Content-Type: application/json

{
    "memberId": "345679890L",
    "memberFirstName": "John",
    "memberLastName": "Doe",
    "amount": 200,
    "referenceNumber": 2020080101,
    "partnerCode": "DBSSG"
}

### enter id of previous data into the url after the slash, see if it returns the above data
GET http://localhost:3002/api/bank/get-transfer/62c16bd657cd7abc0d1712a7
