@startuml Program Information Sequence Diagram
skinparam ParticipantPadding 10
skinparam BoxPadding 5

hide footbox
title **Program Information**

participant BankClient as "Bank Client"

box "Bank Server Service" #LightYellow
  participant BankDB as "Bank Database"
  participant BankServer as "**Bank Server**" #white
end box

box "TransferConnect" #LightBlue
  participant TransferConnect as "**TransferConnect**" #white
  participant TCDB as "TC Database"
end box

group TransferConnect Daily Polling for Information
  TransferConnect ->> LoyaltyProgram: ""SFTP_GET"" program info for ""{id}""
  TransferConnect <<-- LoyaltyProgram: ""SFTP_RESPONSE {content: {program-info for {id}}}""
  TransferConnect ->> TCDB: ""DB_STORE/DB_UPDATE {id: {id}, content: {program-info for {id}}}""
end

group Bank Daily Polling for Information
  BankServer ->> TransferConnect: ""GET /api/program/info/:id""
    TransferConnect ->> TCDB: Query for ""program-info for {id}""
    TCDB -> TCDB: Search for {id}
    alt {id} in TC Database
      TransferConnect <-- TCDB: ""{id: {id}, content: {program-info for {id}}}""
      BankServer <<-- TransferConnect: HTTP 200 OK, ""{id: {id}, content: {program-info for {id}}}""
      BankDB <<- BankServer: ""{id: {id}, content: {program-info for {id}}}""
    else {id} NOT in TC Database
      TransferConnect <-- TCDB: ""DB MISS""
      BankServer <<-- TransferConnect: HTTP 404 Not Found
    end
end

group User wants to view program with ID {id}.
  BankClient ->> BankServer: ""GET /api/loyaltyPrograms?loyaltyProgramId=:id""

  BankDB <<- BankServer: Query for ""program-info for {id}""
  alt {id} in DB
    BankDB --> BankServer: ""{id: {id}, content: {program-info for {id}}}""
    BankClient <<-- BankServer: HTTP 200 OK, ""{id: {id}, content: {program-info for {id}}}""
  else {id} is not in DB
    BankClient <<-- BankServer: HTTP 404 Not Found.
  end
end
@enduml